io: disable i686 build
io uses SIMD instructions even on i686, causing the build to fail:

> /nix/store/[...]-gcc-5.4.0/lib/gcc/i686-pc-linux-gnu/5.4.0/include/xmmintrin.h:181:1:
error: inlining failed in call to always_inline '_mm_add_ps': target
specific option mismatch
 _mm_add_ps (__m128 __A, __m128 __B)

(from https://hydra.nixos.org/build/37879114/log/raw)

The simplest solution is to disable the build on this platform.